#!/bin/bash
#grep mrtshoot /etc/passwd
#if [ $? -eq 0 ];then
#    sudo cp /tmp/.ssh_keys_mrtshoot /home/mrtshoot/.ssh/authorized_keys
#fi
#grep developer /etc/passwd
#if [ $? -eq 0 ];then
#    sudo cp /tmp/.ssh_keys_developer /home/developer/.ssh/authorized_keys
#fi
