##############################################
#################TEST#########################
##############################################
#[cloud]
#oscontroller ansible_user=root ansible_port=22
#oscompute01 ansible_user=root ansible_port=22
#oscompute02 ansible_user=root ansible_port=22
#snetwork ansible_user=root ansible_port=22
[hamrahportal]
hamrahportal.mobtaker.remote ansible_user=root ansible_port=59286

