---
- name: Add Mobotel Users
  hosts: matrix.mobotel.me
  become: yes
  tasks:
     
  - name: Send Userlist
    copy: src=../files/{{ item  }} dest=/usr/local/bin mode=0777
    with_items:
      - "userlist-mobotel"

  - name: Execute Script
    command: sh '/usr/local/bin/matrix-synapse-register-user2'

  - name: Remove Userlist
    file: path=/usr/local/bin/userlist-mobotel state=absent
