---
- name: Send File
  hosts: egom-web.mobtaker.remote
  become: yes
  tasks:
     
  - name: Send Configuration files
    copy: src=../files/{{ item  }} dest=/etc/
    with_items:
      - "rsyslog.conf"

  - name: Enable and Start service
    service: name=rsyslog state=restarted enabled=yes 
