---
- name: Send Allow SSH
  hosts: ALL
  become: yes
  tasks:
    - name: Add Allow Hosts to SSH
      copy: src=../files/{{ item }} dest=/etc mode=0777
      with_items:
        - "hosts.allow"
        - "hosts.deny"

#    - name: Restart SSHD Services
#      service: name=sshd state=restarted enabled=yes
