---
  - name: Send File
    hosts: MOBTAKER.LOCAL
    become: yes
    tasks:
      - name: Copy Zabbix Agent Config File
        copy: src=../temp/docker-compose.yml dest=/opt/prometheus-monitored-device/ mode=0777
