---
- name: Transfer and Execute File
  hosts: MOBTAKER.REMOTE
  become: yes
  tasks:

    - name: Transfer the Files on Remote Host
      copy: src=/opt/init_os/files/{{ item }} dest=/etc/  mode=0777
      with_items:
        - "hosts"

