---
  - name: Install Zabbix Agent
    hosts: zabbix
    become: yes
    tasks:
      - name: Download Zabbix RPM 4.0
        yum: 
          name:
            - https://repo.zabbix.com/zabbix/4.0/rhel/7/x86_64/zabbix-release-4.0-1.el7.noarch.rpm
          state: present
       
      - name: Install zabbix-agent
        yum: name=zabbix-agent state=present

      - name: Enable Zabbix Agent Service
        service: name=zabbix-agent state=restarted enabled=yes

      - name: Open Firewall Ports
        firewalld:
          port: 10050-10051/tcp
          permanent: true
          state: enabled

      - name: Reload Firewall Daemon Service
        service: name=firewalld state=reloaded
