---
- name: Transfer and Execute a SSH Scripts with MrTshoot PlayBooks.
  hosts: MOBTAKER.REMOTE
  become: yes
  tasks:
     - name: Transfer the Script
       copy: src=/opt/init_os/scripts/{{ item }} dest=/tmp  mode=0777
       with_items:
         - "change_user_pass"
         - "temp.sh"

     - name: Install Expect Application
       command: sh '/tmp/temp.sh'

     - name: Execute the Expect
       command: expect /tmp/change_user_pass

     - name: Remove Files
       file: path=/tmp/{{ item }} state=absent
       with_items:
         - "change_user_pass"
         - "temp.sh"
     
#     - name: Restart Service SSHDaemon
#       service: name=sshd state=restarted
